const ChapterTaskTree = require('./../../../src/providers/chapterTaskTree');

var tasks = [ { id: 1,
    taskType: '^',
    name: 'Root Task',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 2,
    taskType: '^',
    parent: [ 1 ],
    name: 'Legal stream',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 3,
    taskType: '^',
    parent: [ 1 ],
    name: 'Product improvement stream',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 4,
    taskType: '^',
    parent: [ 1 ],
    name: 'Research site dev stream',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 5,
    taskType: '±',
    parent: [ 4 ],
    name: 'Site dev by yourself - research',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 6,
    taskType: '^',
    parent: [ 5 ],
    name: 'Site dev by yourself - design',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 7,
    taskType: '^',
    parent: [ 5 ],
    name: 'Site dev by yourself - development',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 8,
    taskType: '§',
    parent: [ 6, 7 ],
    name: 'Site dev by yourself - bugfix',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 9,
    taskType: '±',
    parent: [ 4 ],
    name: 'Site dev by constructor - research',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 24,
    cost: 10 },
  { id: 10,
    taskType: '^',
    parent: [ 9 ],
    name: 'Site dev by constructor - development',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 11,
    taskType: '±',
    parent: [ 4 ],
    name: 'Site dev by studio',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 40,
    cost: 3000 },
  { id: 12,
    taskType: '^',
    parent: [ 11 ],
    name: 'Site dev by studio - review',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 },
  { id: 13,
    taskType: '§',
    parent: [ 5, 9, 11 ],
    name: 'Task after all',
    skills: { hipster: 10, hacker: 10, hustler: 10 },
    hours: 8,
    cost: 0 } ]

const getChapterTaskTree = () => {
  return new ChapterTaskTree({
    tasks
  });
}

module.exports = {
  getChapterTaskTree,
}
